version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-example-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq-example
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


  rabbitmq-example:
    image: rabbitmq:3-management
    container_name: rabbitmq-example
    ports:
      - "5672:5672"
      - "15672:15672"
